// <auto-generated />
using System;
using Biblioteca_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca_API.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260929175009_SacoIntIdListDePrestamo")]
    partial class SacoIntIdListDePrestamo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca_API.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Isbn")
                        .HasColumnType("bigint");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.ToTable("libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "James Clear",
                            Genero = "Desarrollo personal",
                            Isbn = 9783442178582L,
                            Stock = 2,
                            Titulo = "Habitos Atomicos"
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Gabriel García Márquez",
                            Genero = "Realismo mágico",
                            Isbn = 9780307474728L,
                            Stock = 3,
                            Titulo = "Cien Años de Soledad"
                        },
                        new
                        {
                            Id = 3,
                            Autor = "George Orwell",
                            Genero = "Ciencia ficción",
                            Isbn = 9780451524935L,
                            Stock = 4,
                            Titulo = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Antoine de Saint-Exupéry",
                            Genero = "Fábula",
                            Isbn = 9780156012195L,
                            Stock = 5,
                            Titulo = "El Principito"
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Yuval Noah Harari",
                            Genero = "Divulgación histórica",
                            Isbn = 9780062316097L,
                            Stock = 2,
                            Titulo = "Sapiens"
                        });
                });

            modelBuilder.Entity("Biblioteca_API.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaDeDevolucion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaDePrestamo")
                        .HasColumnType("date");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("Biblioteca_API.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "calle falsa 123",
                            Nombre = "Gaston",
                            Telefono = "1928376452"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "pozo de vargas 2258",
                            Nombre = "Marcos",
                            Telefono = "+5491124048045"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "avenida de los patos 43",
                            Nombre = "Valeria",
                            Telefono = "3544344343"
                        });
                });

            modelBuilder.Entity("Biblioteca_API.Models.Libro", b =>
                {
                    b.HasOne("Biblioteca_API.Models.Prestamo", null)
                        .WithMany("Libros")
                        .HasForeignKey("PrestamoId");
                });

            modelBuilder.Entity("Biblioteca_API.Models.Prestamo", b =>
                {
                    b.HasOne("Biblioteca_API.Models.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca_API.Models.Prestamo", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
