// <auto-generated />
using System;
using Biblioteca_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca_API.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260925001111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca_API.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Isbn")
                        .HasColumnType("bigint");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("Biblioteca_API.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatosDeSocioId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDeDevolucion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaDePrestamo")
                        .HasColumnType("date");

                    b.Property<int>("LibroPrestadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatosDeSocioId");

                    b.HasIndex("LibroPrestadoId");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("Biblioteca_API.Models.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Socio");
                });

            modelBuilder.Entity("Biblioteca_API.Models.Prestamo", b =>
                {
                    b.HasOne("Biblioteca_API.Models.Socio", "DatosDeSocio")
                        .WithMany()
                        .HasForeignKey("DatosDeSocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca_API.Models.Libro", "LibroPrestado")
                        .WithMany()
                        .HasForeignKey("LibroPrestadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatosDeSocio");

                    b.Navigation("LibroPrestado");
                });
#pragma warning restore 612, 618
        }
    }
}
